### ISSUE TITLE
Error after update phpBB 3.1.5 to 3.1.6

### ISSUE THREAD

**Issue by Galixte** [ForumHulp/errorpages#6]
Hi @ForumHulp,

a user on the FRENCH support forum reports an error with your extension, after to have updated his board:
```
Fatal error: Uncaught exception 'BadMethodCallException' with message 'Method "Twig_Error::getStatusCode()" does not exist.' in /home/www/rohan/phpbb_dev/vendor/twig/twig/lib/Twig/Error.php:155 Stack trace: #0 /home/www/rohan/phpbb_dev/ext/forumhulp/errorpages/event/listener.php(39): Twig_Error->__call('getStatusCode', Array) #1 /home/www/rohan/phpbb_dev/ext/forumhulp/errorpages/event/listener.php(39): Twig_Error_Loader->getStatusCode() #2 [internal function]: forumhulp\errorpages\event\listener->onKernelException(Object(Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent)) #3 /home/www/rohan/phpbb_dev/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent)) #4 /home/www/rohan/phpbb_dev/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.exceptio...', Object(Symfony\Co in /home/www/rohan/phpbb_dev/vendor/twig/twig/lib/Twig/Error.php on line 155
```

Could you take a look please ?

**Comment by ForumHulp** [comment]
Hi 
Just tried it at 3.1.6 with a not excisting page without problems.
getStatusCode is from Symfony, why did he get this failure?

**Comment by Galixte** [comment]
The error appears during login.

**Comment by ForumHulp** [comment]
Hi Raphaël

 

Can not find a problem at login.

What he should do is switch the error page off and setup debug mode in config.php.

 

Then login in and look at the screen and php log. It should tell what is happening.

 

Greetz

**Comment by Galixte** [comment]
Thanks, it’s fixed.

**Comment by Galixte** [comment]
Oups ! reopened, i wrote on the wrong page.

**Comment by ForumHulp** [comment]
Wondering what is really was?

**Comment by Galixte** [comment]
i have asked your recommendations (activate the debug mode) to the user, i wait his answer.
